<?php namespace App\Database\Migrations;

class AddIndicatorsBseceavii extends \CodeIgniter\Database\Migration {

        private $table = 'parameter_items';
        public function up()
        {
          //PARAMETER A: ADMINISTRATION 2501
          $data = [
              [
                  'id' => 2501,
                  'parameter_item' => 'S.1. The organizational structure of the library is well-defined.',
                  'description' => 'S.1. The organizational structure of the library is well-defined.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2502,
                  'parameter_item' => 'S.2. The development of the library goals and objectives is the responsibility of the library head and staff with the approval of the Head of the institution',
                  'description' => 'S.2. The development of the library goals and objectives is the responsibility of the library head and staff with the approval of the Head of the institution',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2503,
                  'parameter_item' => 'S.3. There is a Library Board/Committee which sets library policies, rules and procedures and periodically reviews them. ',
                  'description' => 'S.3. There is a Library Board/Committee which sets library policies, rules and procedures and periodically reviews them. ',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2504,
                  'parameter_item' => 'S.4. There is a duly approved and widely disseminated Library Manual or written policies and procedures covering the library’s internal administration and operation',
                  'description' => 'S.4. There is a duly approved and widely disseminated Library Manual or written policies and procedures covering the library’s internal administration and operation',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2505,
                  'parameter_item' => 'I.1.  The library develops an explicit statement of its goals and objectives in conformity with the mandate of the institution.',
                  'description' => 'I.1.  The library develops an explicit statement of its goals and objectives in conformity with the mandate of the institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2506,
                  'parameter_item' => 'I.2. The library is administered and supervised by:',
                  'description' => 'I.2. The library is administered and supervised by:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2507,
                  'parameter_item' => 'I.2.1. a full-time professional licensed librarian',
                  'description' => 'I.2.1. a full-time professional licensed librarian',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '2506',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2508,
                  'parameter_item' => 'I.2.2. at least a master’s degree holder in MS Library and Information Science or MAEd/MA in Library Science.',
                  'description' => 'I.2.2. at least a master’s degree holder in MS Library and Information Science or MAEd/MA in Library Science.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '2506',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2509,
                  'parameter_item' => 'I.3 The Head Librarian directs and supervises the total operation of the library and is responsible for the administration of its resources and services.',
                  'description' => 'I.3 The Head Librarian directs and supervises the total operation of the library and is responsible for the administration of its resources and services.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2510,
                  'parameter_item' => 'I.4. The Head Librarian, preferably with an academic rank, actively participates in the academic and administrative activities of the institution.',
                  'description' => 'I.4. The Head Librarian, preferably with an academic rank, actively participates in the academic and administrative activities of the institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2511,
                  'parameter_item' => 'I.5. The annual accomplishments and other reports of the library are promptly submitted to the higher offices concerned.',
                  'description' => 'I.5. The annual accomplishments and other reports of the library are promptly submitted to the higher offices concerned.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2512,
                  'parameter_item' => 'I.6. A Library Development Plan is prepared in consultation with the institution’s officials  and stakeholders.',
                  'description' => 'I.6. A Library Development Plan is prepared in consultation with the institution’s officials  and stakeholders.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2513,
                  'parameter_item' => 'O.1. The goals and objectives of the library are satisfactorily attained.',
                  'description' => 'O.1. The goals and objectives of the library are satisfactorily attained.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2514,
                  'parameter_item' => 'O.2. The library organizational structure is well-designed and effectively implemented.',
                  'description' => 'O.2. The library organizational structure is well-designed and effectively implemented.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '28',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER B: ADMINISTRATIVE STAFF
              [
                  'id' => 2515,
                  'parameter_item' => 'S.1. The library has staff with the following qualifications:',
                  'description' => 'S.1. The library has staff with the following qualifications:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2516,
                  'parameter_item' => 'S.1.1. BS in Library and Information Science for the College/Academic Unit  Library',
                  'description' => 'S.1.1. BS in Library and Information Science for the College/Academic Unit  Library',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '2515',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2517,
                  'parameter_item' => 'S.1.2. Ms in Library and Information Science or MAED/MA in Library Science for the Institution.',
                  'description' => 'S.1.2. Ms in Library and Information Science or MAED/MA in Library Science for the Institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '2515',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2518,
                  'parameter_item' => 'S.2. The library meets the required number of qualified and licensed librarians and staff to meet the needs of the school population with the ratio of:',
                  'description' => 'S.2. The library meets the required number of qualified and licensed librarians and staff to meet the needs of the school population with the ratio of:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2519,
                  'parameter_item' => 'S.2.1. one (1) Licensed Librarian with two (2) full time staff for the first 500 – student population',
                  'description' => 'S.2.1. one (1) Licensed Librarian with two (2) full time staff for the first 500 – student population',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '2518',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2520,
                  'parameter_item' => 'S.2.2. one (1) additional full time Professional Librarian with one (1) full time staff for every additional 1,000 students. ',
                  'description' => 'S.2.2. one (1) additional full time Professional Librarian with one (1) full time staff for every additional 1,000 students. ',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '2518',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2521,
                  'parameter_item' => 'S.3. There is a continuing staff development program with the corresponding financial assistance from the institution.',
                  'description' => 'S.3. There is a continuing staff development program with the corresponding financial assistance from the institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2522,
                  'parameter_item' => 'I.1. The library staff compensation, retirement, and fringe benefits, as well as other privileges, are granted in accordance with existing government laws and institutional policies.',
                  'description' => 'I.1. The library staff compensation, retirement, and fringe benefits, as well as other privileges, are granted in accordance with existing government laws and institutional policies.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2523,
                  'parameter_item' => 'O.1. The librarians are qualified',
                  'description' => 'O.1. The librarians are qualified',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '29',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER C: COLLECTION DEVELOPMENT, ORGANIZATION AND PRESERVATION
              [
                  'id' => 2524,
                  'parameter_item' => 'S.1. There is a written Collection Development Policy',
                  'description' => 'S.1. There is a written Collection Development Policy',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2525,
                  'parameter_item' => 'S.2. There is a core collection of at least',
                  'description' => 'S.2. There is a core collection of at least',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2526,
                  'parameter_item' => 'S.2.1. 5,000 titles for the Academic Unit Library',
                  'description' => 'S.2.1. 5,000 titles for the Academic Unit Library',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '2525',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2527,
                  'parameter_item' => 'S.2.2. 10,000 titles that support the instruction, research and other programs  for an Institution Library',
                  'description' => 'S.2.2. 10,000 titles that support the instruction, research and other programs  for an Institution Library',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '2525',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2528,
                  'parameter_item' => 'S.3. Twenty percent (20%) of the library holdings are of current edition, i.e with copyright within the last 5 years.',
                  'description' => 'S.3. Twenty percent (20%) of the library holdings are of current edition, i.e with copyright within the last 5 years.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2529,
                  'parameter_item' => 'S.4. The Non-print, digital and electronics resources are available.',
                  'description' => 'S.4. The Non-print, digital and electronics resources are available.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2530,
                  'parameter_item' => 'S.5. There is an integrated library system.',
                  'description' => 'S.5. There is an integrated library system.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2531,
                  'parameter_item' => 'S.6. There are provisions for the preservation, general care, and upkeep of library resources.',
                  'description' => 'S.6. There are provisions for the preservation, general care, and upkeep of library resources.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2532,
                  'parameter_item' => 'I.1. The Collection Development Policy is regularly reviewed and evaluated by the Library Committee.    ',
                  'description' => 'I.1. The Collection Development Policy is regularly reviewed and evaluated by the Library Committee.    ',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2533,
                  'parameter_item' => 'I.2.  The library collection and services support the mission and vision of the  Institution, goals of the College/Academic Unit and objectives of the Program.',
                  'description' => 'I.2.  The library collection and services support the mission and vision of the  Institution, goals of the College/Academic Unit and objectives of the Program.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2534,
                  'parameter_item' => 'I.3. The library provides sufficient research books and materials to supplement the client’s curricular needs.',
                  'description' => 'I.3. The library provides sufficient research books and materials to supplement the client’s curricular needs.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2535,
                  'parameter_item' => 'I.4. The library maintains an extensive (15% of the total) Filipiniana collection',
                  'description' => 'I.4. The library maintains an extensive (15% of the total) Filipiniana collection',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2536,
                  'parameter_item' => 'I.5. The library provides 3-5 book/journal titles for professional subjects in the major fields of specialization.',
                  'description' => 'I.5. The library provides 3-5 book/journal titles for professional subjects in the major fields of specialization.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2537,
                  'parameter_item' => 'I.6. The library collection is organized according to an accepted scheme of classification and standard code of cataloging.',
                  'description' => 'I.6. The library collection is organized according to an accepted scheme of classification and standard code of cataloging.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2538,
                  'parameter_item' => 'I.7. Regular weeding-out program is conducted to maintain a relevant and  updated collection.',
                  'description' => 'I.7. Regular weeding-out program is conducted to maintain a relevant and  updated collection.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2539,
                  'parameter_item' => 'I.8. The quality and quantity of library materials and resources conform with the  set for a particular academic program.',
                  'description' => 'I.8. The quality and quantity of library materials and resources conform with the  set for a particular academic program.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2540,
                  'parameter_item' => 'O.1. The library core collection is adequate, updated and well-balanced.',
                  'description' => 'O.1. The library core collection is adequate, updated and well-balanced.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2541,
                  'parameter_item' => 'O.2. The professional books, journals and electronic resources for the program are sufficient',
                  'description' => 'O.2. The professional books, journals and electronic resources for the program are sufficient',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '30',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER D: SERVICES AND UTILIZATION
              [
                  'id' => 2542,
                  'parameter_item' => 'S.1. The Library has information services pertinent to the institution’s requirements.',
                  'description' => 'S.1. The Library has information services pertinent to the institution’s requirements.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2543,
                  'parameter_item' => 'I.1. The following services/programs are provided:',
                  'description' => 'I.1. The following services/programs are provided:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2544,
                  'parameter_item' => 'I.1.1. functional and interactive library web page',
                  'description' => 'I.1.1. functional and interactive library web page',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2545,
                  'parameter_item' => 'I.1.2. integrated library system',
                  'description' => 'I.1.2. integrated library system',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2546,
                  'parameter_item' => 'I.1.3. on-line public access (OPAC)',
                  'description' => 'I.1.3. on-line public access (OPAC)',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2547,
                  'parameter_item' => 'I.1.4. circulation on-line',
                  'description' => 'I.1.4. circulation on-line',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2548,
                  'parameter_item' => 'I.1.5. computerized cataloging',
                  'description' => 'I.1.5. computerized cataloging',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2549,
                  'parameter_item' => 'I.1.6. inventory reporting',
                  'description' => 'I.1.6. inventory reporting',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2550,
                  'parameter_item' => 'I.1.7. serials control',
                  'description' => 'I.1.7. serials control',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2551,
                  'parameter_item' => 'I.1.8.  internet searching',
                  'description' => 'I.1.8.  internet searching',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2552,
                  'parameter_item' => 'I.1.9.  CD-ROM',
                  'description' => 'I.1.9.  CD-ROM',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2553,
                  'parameter_item' => 'I.1.10. on-line database',
                  'description' => 'I.1.10. on-line database',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2554,
                  'parameter_item' => 'I.1.11. photocopying',
                  'description' => 'I.1.11. photocopying',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2555,
                  'parameter_item' => 'I.1.12.  bar coding',
                  'description' => 'I.1.12.  bar coding',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '2543',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2556,
                  'parameter_item' => 'I.2. The library opens at least 54 hours per week for the College/Academic Unit or 60 hours per week for the Institution.',
                  'description' => 'I.2. The library opens at least 54 hours per week for the College/Academic Unit or 60 hours per week for the Institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2557,
                  'parameter_item' => 'I.3. The library promotes and disseminates its program through a regular announcement  of its new acquisitions of print materials (books, journals, magazines), resources,facilities, and services.',
                  'description' => 'I.3. The library promotes and disseminates its program through a regular announcement of its new acquisitions of print materials (books, journals, magazines), resources, facilities, and services.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2558,
                  'parameter_item' => 'I.4. Librarians and staff are available during library hours to assist and provide library services',
                  'description' => 'I.4. Librarians and staff are available during library hours to assist and provide library services',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2559,
                  'parameter_item' => 'I.5. Statistical data on the utilization of various resources and services are compiled and used to improve the library collection and operations.',
                  'description' => 'I.5. Statistical data on the utilization of various resources and services are compiled and used to improve the library collection and operations.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2560,
                  'parameter_item' => 'O.1.The library services are efficiently and effectively provided.',
                  'description' => 'O.1. The library services are efficiently and effectively provided.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2561,
                  'parameter_item' => 'O.2. The library users are satisfied with library services',
                  'description' => 'O.2. The library users are satisfied with library services',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '31',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER E: PHYSICAL SET-UP AND FACILITIES
              [
                  'id' => 2562,
                  'parameter_item' => 'S.1. The library is strategically located and accessible to students, faculty and other clients',
                  'description' => 'S.1. The library is strategically located and accessible to students, faculty and other clients',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2563,
                  'parameter_item' => 'S.2. The library is systematically planned to allow future expansion',
                  'description' => 'S.2. The library is systematically planned to allow future expansion',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2564,
                  'parameter_item' => 'S.3. The size of the library meets standard requirements considering the present enrollment and future expansion',
                  'description' => 'S.3. The size of the library meets standard requirements considering the present enrollment and future expansion',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2565,
                  'parameter_item' => 'S.4. The reading room can accommodate at least 10% of the school enrollment at any given time',
                  'description' => 'S.4. The reading room can accommodate at least 10% of the school enrollment at any given time',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2566,
                  'parameter_item' => 'S.5. Space is provided for print resources as well as work stations for electronic resources',
                  'description' => 'S.5. Space is provided for print resources as well as work stations for electronic resources',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2567,
                  'parameter_item' => 'S.6. Space is provided for the librarians’ office, staff room, technical room, etc',
                  'description' => 'S.6. Space is provided for the librarians’ office, staff room, technical room, etc',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2568,
                  'parameter_item' => 'S.7. Ramps for the physically disabled are provided',
                  'description' => 'S.7. Ramps for the physically disabled are provided',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2569,
                  'parameter_item' => 'S.8. The library meets the required and standard-sized furniture and equipment',
                  'description' => 'S.8. The library meets the required and standard-sized furniture and equipment',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2570,
                  'parameter_item' => 'S.9. The following library furniture and equipment are available',
                  'description' => 'S.9. The following library furniture and equipment are available',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2571,
                  'parameter_item' => 'S.9.1.  adjustable/movable shelves',
                  'description' => 'S.9.1.  adjustable/movable shelves',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2572,
                  'parameter_item' => 'S.9.2.  magazine display shelves',
                  'description' => 'S.9.2.  magazine display shelves',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2573,
                  'parameter_item' => 'S.9.3.  newspaper racks',
                  'description' => 'S.9.3.  newspaper racks',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2574,
                  'parameter_item' => 'S.9.4.  standard tables and chairs',
                  'description' => 'S.9.4.  standard tables and chairs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2575,
                  'parameter_item' => 'S.9.5.  carrels for individual study',
                  'description' => 'S.9.5.  carrels for individual study',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2576,
                  'parameter_item' => 'S.9.6.  desks and chairs for staff',
                  'description' => 'S.9.6.  desks and chairs for staff',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2577,
                  'parameter_item' => 'S.9.7.  charging desk',
                  'description' => 'S.9.7.  charging desk',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2578,
                  'parameter_item' => 'S.9.8.  dictionary stand',
                  'description' => 'S.9.8.  dictionary stand',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2579,
                  'parameter_item' => 'S.9.9.  atlas stand',
                  'description' => 'S.9.9.  atlas stand',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2580,
                  'parameter_item' => 'S.9.10.  bulletin boards and display cabinets',
                  'description' => 'S.9.10.  bulletin boards and display cabinets',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2581,
                  'parameter_item' => 'S.9.11.  vertical file cabinets',
                  'description' => 'S.9.11.  vertical file cabinets',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2582,
                  'parameter_item' => 'S.9.12.  book racks',
                  'description' => 'S.9.12.  book racks',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2583,
                  'parameter_item' => 'S.9.13.  map stands/cabinets',
                  'description' => 'S.9.13.  map stands/cabinets',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2584,
                  'parameter_item' => 'S.9.14.  cardex/ rotadex or any filing equipment for periodical records',
                  'description' => 'S.9.14.  cardex/ rotadex or any filing equipment for periodical records',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2585,
                  'parameter_item' => 'S.9.15.  typewriters',
                  'description' => 'S.9.15.  typewriters',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2586,
                  'parameter_item' => 'S.9.16.  computers with printers',
                  'description' => 'S.9.16.  computers with printers',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2587,
                  'parameter_item' => 'S.9.17.  others (please specify)',
                  'description' => 'S.9.17.  others (please specify)',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '2570',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2588,
                  'parameter_item' => 'S.10. The library is well lighted',
                  'description' => 'S.10. The library is well lighted',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2589,
                  'parameter_item' => 'S.11. The library is well-ventilated',
                  'description' => 'S.11. The library is well-ventilated',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2590,
                  'parameter_item' => 'S.12. The atmosphere is conducive to learning',
                  'description' => 'S.12. The atmosphere is conducive to learning',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2591,
                  'parameter_item' => 'S.13. Fire extinguishers and a local fire alarm system are available.',
                  'description' => 'S.13. Fire extinguishers and a local fire alarm system are available.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2592,
                  'parameter_item' => 'S.14. The Library employs a system for security and control of library resources',
                  'description' => 'S.14. The Library employs a system for security and control of library resources',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2593,
                  'parameter_item' => 'I.1. IT software and multi-media equipment are utilized',
                  'description' => 'I.1. IT software and multi-media equipment are utilized',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2594,
                  'parameter_item' => 'O.1. The environment in the library is conducive to learning',
                  'description' => 'O.1. The environment in the library is conducive to learning',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2595,
                  'parameter_item' => 'O.2. The library facilities are well-maintained and aesthetically designed',
                  'description' => 'O.2. The library facilities are well-maintained and aesthetically designed',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '32',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER F: FINANCIAL SUPPORT
              [
                  'id' => 2596,
                  'parameter_item' => 'S.1. The institution has a  regular and realistic budget for the library',
                  'description' => 'S.1. The institution has a  regular and realistic budget for the library',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '33',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2597,
                  'parameter_item' => 'I.1. The Head Librarian and staff, in coordination with other officials of the institution, prepare and manage the annual library budget',
                  'description' => 'I.1. The Head Librarian and staff, in coordination with other officials of the institution, prepare and manage the annual library budget',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '33',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2598,
                  'parameter_item' => 'I.2. All fees and funds allocated for library resources and services are utilized solely for such purposes and are properly audited.',
                  'description' => 'I.2. All fees and funds allocated for library resources and services are utilized solely for such purposes and are properly audited.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '33',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2599,
                  'parameter_item' => 'I.3. Other sources of financial assistance are sought',
                  'description' => 'I.3. Other sources of financial assistance are sought',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '33',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2600,
                  'parameter_item' => 'O.1. The financial support from fiduciary, supplemental and external funds is adequate',
                  'description' => 'O.1. The financial support from fiduciary, supplemental and external funds is adequate',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '33',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              // /PARAMETER G LINAGES
              [
                  'id' => 2601,
                  'parameter_item' => 'S.1 The Library is on the mailing list of agencies, foundations, etc., for exchange of publications and other books and journals donations',
                  'description' => 'S.1 The Library is on the mailing list of agencies, foundations, etc., for exchange of publications and other books and journals donations',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '34',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2602,
                  'parameter_item' => 'I.1 Linkages with other institutions and funding agencies are explored and established for purposes of enhancing library facilities and resources',
                  'description' => 'I.1 Linkages with other institutions and funding agencies are explored and established for purposes of enhancing library facilities and resources',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '34',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2603,
                  'parameter_item' => 'I.2 The library establishes consortia, networking and resource sharing with other institutions and library collaborative activities',
                  'description' => 'I.2 The library establishes consortia, networking and resource sharing with other institutions and library collaborative activities',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '34',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2604,
                  'parameter_item' => 'O.1 Library resource sharing and linkages are well-established',
                  'description' => 'O.1 Library resource sharing and linkages are well-established',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '17',
                  'template_parameter_id' => '34',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
          ];
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $builder->insertBatch($data);
        }

        public function down()
        {
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $db->simpleQuery('DELETE FROM '.$this->table.' WHERE id >= 2501 AND id <= 2604');
        }
}
