<?php namespace App\Database\Migrations;

class AddIndicatorsBseceax extends \CodeIgniter\Database\Migration {

        private $table = 'parameter_items';
        public function up()
        {
          //PARAMETER A: ORGANIZATION 3201
          $data = [
              [
                  'id' => 3201,
                  'parameter_item' => 'S.1.	The institution has an organizational structure approved by the Board  of Regents/Trustees (BOR/BOT).',
                  'description' => 'S.1.	The institution has an organizational structure approved by the Board of Regents/Trustees (BOR/BOT).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3202,
                  'parameter_item' => 'S.2. Every office/unit in the organizational structure has functions approved by the (BOR/BOT).',
                  'description' => 'S.2. Every office/unit in the organizational structure has functions approved by the (BOR/BOT).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3203,
                  'parameter_item' => 'I.1.	The institution is subdivided into administrative units in accordance with the organizational structure.',
                  'description' => 'I.1.	The institution is subdivided into administrative units in accordance with the organizational structure.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3204,
                  'parameter_item' => 'I.2.	The functions, duties and responsibilities of administrative staff in each unit/office are identified and carried out.',
                  'description' => 'I.2.	The functions, duties and responsibilities of administrative staff in each unit/office are identified and carried out.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3205,
                  'parameter_item' => 'I.3	The Board of Regents/Trustees is supportive with the growth and development of the institution.',
                  'description' => 'I.3	The Board of Regents/Trustees is supportive with the growth and development of the institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3206,
                  'parameter_item' => 'I.4.	The Academic and Administrative Councils exercise their powers and perform their functions.',
                  'description' => 'I.4.	The Academic and Administrative Councils exercise their powers and perform their functions.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3207,
                  'parameter_item' => 'I.5.	The flow of communication among and within units/departments is observed.',
                  'description' => 'I.5.	The flow of communication among and within units/departments is observed.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3208,
                  'parameter_item' => 'O.1.	The institution has a well-designed and functional organizational structure.',
                  'description' => 'O.1.	The institution has a well-designed and functional organizational structure.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '41',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER B: ACADEMIC ADMINISTRATION
              [
                  'id' => 3209,
                  'parameter_item' => 'S.1.	The Dean/Academic Unit Head possesses the required educational qualifications, experience and other prescribed requirements to administer the College/Academic Unit as follows:',
                  'description' => 'S.1.	The Dean/Academic Unit Head possesses the required educational qualifications, experience and other prescribed requirements to administer the College/Academic Unit as follows:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3210,
                  'parameter_item' => 'S.1.1.	holder of baccalaureate and master’s degree in engineering, preferably in the Bachelor of Science in Electronics Engineering',
                  'description' => 'S.1.1.	holder of baccalaureate and master’s degree in engineering, preferably in the Bachelor of Science in Electronics Engineering',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3209',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3211,
                  'parameter_item' => 'S.1.2.	preferably holder of doctorate degree in engineering or related fields',
                  'description' => 'S.1.2.	preferably holder of doctorate degree in engineering or related fields',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3209',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3212,
                  'parameter_item' => 'S.1.3.	Must have a minimum teaching experience of not less than five (5) years',
                  'description' => 'S.1.3.	Must have a minimum teaching experience of not less than five (5) years',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3209',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3213,
                  'parameter_item' => 'S.1.4.	At least five (5) years administrative experience and at least five (5) field experience and',
                  'description' => 'S.1.4.	At least five (5) years administrative experience and at least five (5) field experience and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3209',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3214,
                  'parameter_item' => 'S.1.5.	registered engineer.',
                  'description' => 'S.1.5.	registered engineer.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3209',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3215,
                  'parameter_item' => 'S.2.	The Department Chair/s, or their equivalent has appropriate/relevant educational qualification and experience.',
                  'description' => 'S.2.	The Department Chair/s, or their equivalent has appropriate/relevant educational qualification and experience.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3216,
                  'parameter_item' => 'I.1.	The Dean is assisted by Department Chair/s or their equivalent with appropriate/relevant educational qualification and experience.',
                  'description' => 'I.1.	The Dean is assisted by Department Chair/s or their equivalent with appropriate/relevant educational qualification and experience.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3217,
                  'parameter_item' => 'I.2.	The Dean implements a supervisory program.',
                  'description' => 'I.2.	The Dean implements a supervisory program.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3218,
                  'parameter_item' => 'I.3.	The Dean participates in the recruitment and promotion of faculty and support staff.',
                  'description' => 'I.3.	The Dean participates in the recruitment and promotion of faculty and support staff.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3219,
                  'parameter_item' => 'I.4.	The Dean, the faculty and the administration work together for the improvement of the College/Academic Unit, particularly in:',
                  'description' => 'I.4.	The Dean, the faculty and the administration work together for the improvement of the College/Academic Unit, particularly in:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3220,
                  'parameter_item' => 'I.4.1.	setting standards and targets',
                  'description' => 'I.4.1.	setting standards and targets',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3221,
                  'parameter_item' => 'I.4.2.	planning of programs and other related activities',
                  'description' => 'I.4.2.	planning of programs and other related activities',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3222,
                  'parameter_item' => 'I.4.3.	implementing, monitoring and evaluation of plans, programs, and other related activities',
                  'description' => 'I.4.3.	implementing, monitoring and evaluation of plans, programs, and other related activities',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3223,
                  'parameter_item' => 'I.4.4.	establishing linkages, partnerships and networking activities',
                  'description' => 'I.4.4.	establishing linkages, partnerships and networking activities',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3224,
                  'parameter_item' => 'I.4.5.	providing opportunities for professional growth and development of the faculty and staff',
                  'description' => 'I.4.5.	providing opportunities for professional growth and development of the faculty and staff',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3225,
                  'parameter_item' => 'I.4.6.	preparing policies and guidelines on the internal administration and operation of the College/Academic Unit and',
                  'description' => 'I.4.6.	preparing policies and guidelines on the internal administration and operation of the College/Academic Unit and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3226,
                  'parameter_item' => 'I.4.7.	preparing guidelines on the proper use and maintenance of facilities, equipment, supplies and materials.',
                  'description' => 'I.4.7.	preparing guidelines on the proper use and maintenance of facilities, equipment, supplies and materials.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '3219',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3227,
                  'parameter_item' => 'I.5.	Definite criteria and procedures in the selection and promotion of the most qualified faculty and staff are observed.	',
                  'description' => 'I.5.	Definite criteria and procedures in the selection and promotion of the most qualified faculty and staff are observed.	',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3228,
                  'parameter_item' => 'I.6.	The Dean, faculty, staff, and students pursue collaborative activities in generating resources and income, and in implementing cost-	effective measures.',
                  'description' => 'I.6.	The Dean, faculty, staff, and students pursue collaborative activities in generating resources and income, and in implementing cost-	effective measures.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3229,
                  'parameter_item' => 'I.7.	The Dean implements policies and procedures on internal administration and operations of the College/Academic Unit.',
                  'description' => 'I.7.	The Dean implements policies and procedures on internal administration and operations of the College/Academic Unit.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3230,
                  'parameter_item' => 'O.1.	The College/Academic Unit is efficiently and effectively managed.',
                  'description' => 'O.1.	The College/Academic Unit is efficiently and effectively managed.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '50',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER C: STUDENT ADMINISTRATION
              [
                  'id' => 3231,
                  'parameter_item' => 'S.1.	The institution has an approved and printed Student Handbook/Manual containing policies and guidelines on the following aspects of student life',
                  'description' => 'S.1.	The institution has an approved and printed Student Handbook/Manual containing policies and guidelines on the following aspects of student life',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3232,
                  'parameter_item' => 'S.1.1.	admission and retention policies',
                  'description' => 'S.1.1.	admission and retention policies',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3233,
                  'parameter_item' => 'S.1.2.	registration requirements',
                  'description' => 'S.1.2.	registration requirements',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3234,
                  'parameter_item' => 'S.1.3.	school fees',
                  'description' => 'S.1.3.	school fees',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3235,
                  'parameter_item' => 'S.1.4.	academic load',
                  'description' => 'S.1.4.	academic load',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3236,
                  'parameter_item' => 'S.1.5.	transfers',
                  'description' => 'S.1.5.	transfers',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3237,
                  'parameter_item' => 'S.1.6.	residence, course work, scholastic and graduation requirements',
                  'description' => 'S.1.6.	residence, course work, scholastic and graduation requirements',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3238,
                  'parameter_item' => 'S.1.7.	examination and grading system',
                  'description' => 'S.1.7.	examination and grading system',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3239,
                  'parameter_item' => 'S.1.8.	scholarships/grants/assistantships',
                  'description' => 'S.1.8.	scholarships/grants/assistantships',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3240,
                  'parameter_item' => 'S.1.9.	shifting and adding/dropping of course',
                  'description' => 'S.1.9.	shifting and adding/dropping of course',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3241,
                  'parameter_item' => 'S.1.10. code of conduct and discipline',
                  'description' => 'S.1.10. code of conduct and discipline',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3242,
                  'parameter_item' => 'S.1.11. attendance and',
                  'description' => 'S.1.11. attendance and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3243,
                  'parameter_item' => 'S.1.12. others (please specify) ________.',
                  'description' => 'S.1.12. others (please specify) ________.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '3231',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3244,
                  'parameter_item' => 'I.1.	Students are provided opportunities to participate in the planning and implementation of activities concerning their welfare.',
                  'description' => 'I.1.	Students are provided opportunities to participate in the planning and implementation of activities concerning their welfare.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3245,
                  'parameter_item' => 'I.2.	Concerned officials, faculty and staff act promptly on requests, needs and problems of the students.',
                  'description' => 'I.2.	Concerned officials, faculty and staff act promptly on requests, needs and problems of the students.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3246,
                  'parameter_item' => 'I.3.	The administration, faculty, staff, and students work harmoniously and maintain good working relationship.',
                  'description' => 'I.3.	The administration, faculty, staff, and students work harmoniously and maintain good working relationship.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3247,
                  'parameter_item' => 'O.1.	The institution has an effective and functional Student Administration.',
                  'description' => 'O.1.	The institution has an effective and functional Student Administration.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3248,
                  'parameter_item' => 'O.2.	Policy implementation is efficient.',
                  'description' => 'O.2.	Policy implementation is efficient.',
                  'document_needed_list' => '51',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '51',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER D: FINANCIAL MANAGEMENT
              [
                  'id' => 3249,
                  'parameter_item' => 'S.1.	The institution has an approved Financial Development Plan (FDP).',
                  'description' => 'S.1.	The institution has an approved Financial Development Plan (FDP).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3250,
                  'parameter_item' => 'S.2.	The institution has specific budgetary allotment for the following:',
                  'description' => 'S.2.	The institution has specific budgetary allotment for the following:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3251,
                  'parameter_item' => 'S.2.1.	personal services',
                  'description' => 'S.2.1.	personal services',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3250',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3252,
                  'parameter_item' => 'S.2.2.	Maintenance and Other Operating Expenses (MODE)',
                  'description' => 'S.2.2.	Maintenance and Other Operating Expenses (MODE)',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3250',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3253,
                  'parameter_item' => 'S.2.3.	capital outlay and',
                  'description' => 'S.2.3.	capital outlay and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3250',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3254,
                  'parameter_item' => 'S.2.4.	special projects',
                  'description' => 'S.2.4.	special projects',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3250',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3255,
                  'parameter_item' => 'S.2.5.	The approved budget is in consonance with the FDP.',
                  'description' => 'S.2.5.	The approved budget is in consonance with the FDP.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3250',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3256,
                  'parameter_item' => 'I.1.	The institution maintains a Financial Management Office managed by qualified and competent personnel.',
                  'description' => 'I.1.	The institution maintains a Financial Management Office managed by qualified and competent personnel.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3257,
                  'parameter_item' => 'I.2.	The financial management personnel are responsible for the efficient management of the financial resources/funds of the institution.',
                  'description' => 'I.2.	The financial management personnel are responsible for the efficient management of the financial resources/funds of the institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3258,
                  'parameter_item' => 'I.3.	The administrative officials, faculty, staff and student representatives participate in the budget preparation and in the procurement program of the institution.',
                  'description' => 'I.3.	The administrative officials, faculty, staff and student representatives participate in the budget preparation and in the procurement program of the institution.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3259,
                  'parameter_item' => 'I.4.	The budget of the institution is fairly and objectively allocated.',
                  'description' => 'I.4.	The budget of the institution is fairly and objectively allocated.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3260,
                  'parameter_item' => 'I.5	The institution allocates funds for the following student services and activities:',
                  'description' => 'I.5	The institution allocates funds for the following student services and activities:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3261,
                  'parameter_item' => 'I.5.1.	cultural development',
                  'description' => 'I.5.1.	cultural development',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3262,
                  'parameter_item' => 'I.5.2.	athletic and sports development',
                  'description' => 'I.5.2.	athletic and sports development',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3263,
                  'parameter_item' => 'I.5.3.	medical and dental services',
                  'description' => 'I.5.3.	medical and dental services',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3264,
                  'parameter_item' => 'I.5.4.	library',
                  'description' => 'I.5.4.	library',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3265,
                  'parameter_item' => 'I.5.5.	student body organization',
                  'description' => 'I.5.5.	student body organization',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3266,
                  'parameter_item' => 'I.5.6.	guidance and counseling',
                  'description' => 'I.5.6.	guidance and counseling',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3267,
                  'parameter_item' => 'I.5.7.	improvement of laboratories/shops',
                  'description' => 'I.5.7.	improvement of laboratories/shops',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3268,
                  'parameter_item' => 'I.5.8.	repair and maintenance of facilities and equipment',
                  'description' => 'I.5.8.	repair and maintenance of facilities and equipment',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3269,
                  'parameter_item' => 'I.5.9.	purchase of new equipment, supplies and materials',
                  'description' => 'I.5.9.	purchase of new equipment, supplies and materials',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3270,
                  'parameter_item' => 'I.5.10. replacement of old and unserviceable equipment',
                  'description' => 'I.5.10. replacement of old and unserviceable equipment',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3271,
                  'parameter_item' => 'I.5.11. construction of new facilities, as needed',
                  'description' => 'I.5.11. construction of new facilities, as needed',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3272,
                  'parameter_item' => 'I.5.12. improvement/expansion of physical plant',
                  'description' => 'I.5.12. improvement/expansion of physical plant',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3273,
                  'parameter_item' => 'I.5.13. extension and community services',
                  'description' => 'I.5.13. extension and community services',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3274,
                  'parameter_item' => 'I.5.14. disaster and risks reduction and',
                  'description' => 'I.5.14. disaster and risks reduction and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3275,
                  'parameter_item' => 'I.5.15. auxiliary services, etc.',
                  'description' => 'I.5.15. auxiliary services, etc.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '3260',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3276,
                  'parameter_item' => 'I.6.	The budget allotted for specific expenditures indicated in item 1.5 is in consonance with existing policies and guidelines.',
                  'description' => 'I.6.	The budget allotted for specific expenditures indicated in item 1.5 is in consonance with existing policies and guidelines.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3277,
                  'parameter_item' => 'O.1.	The institution has a sound and effective financial management system.',
                  'description' => 'O.1.	The institution has a sound and effective financial management system.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '52',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER E: FINANCIAL MANAGEMENT
              [
                  'id' => 3278,
                  'parameter_item' => 'S.1.	The institution has an approved procurement management system in consonance with the Revised IRR of RA 9184 (Government Procurement Reform Act).',
                  'description' => 'S.1.	The institution has an approved procurement management system in consonance with the Revised IRR of RA 9184 (Government Procurement Reform Act).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3279,
                  'parameter_item' => 'S.2.	The institution has a system for the proper disposal of non-	serviceable and condemned equipment, supplies and materials.',
                  'description' => 'S.2.	The institution has a system for the proper disposal of non-	serviceable and condemned equipment, supplies and materials.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3280,
                  'parameter_item' => 'S.3.	The office has a storeroom for keeping and storing all equipment, supplies and materials purchased.',
                  'description' => 'S.3.	The office has a storeroom for keeping and storing all equipment, supplies and materials purchased.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3281,
                  'parameter_item' => 'I.1.	The institution maintains a Supply Management Office (SMO) managed by qualified staff with specific functions and responsibilities.',
                  'description' => 'I.1.	The institution maintains a Supply Management Office (SMO) managed by qualified staff with specific functions and responsibilities.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3282,
                  'parameter_item' => 'I.2.	The Bids and Awards Committee (BAC) is responsible for the procurement and deliveries of needed equipment, supplies and materials in accordance with approved Annual Procurement Plan (APP) and Project Procurement Management Plan (PPMP).',
                  'description' => 'I.2.	The Bids and Awards Committee (BAC) is responsible for the procurement and deliveries of needed equipment, supplies and materials in accordance with approved Annual Procurement Plan (APP) and Project Procurement Management Plan (PPMP).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3283,
                  'parameter_item' => 'I.3.	The Bids and Awards Committee (BAC) perform its tasks and responsibilities in accordance with recent procurement policies and official issuances.',
                  'description' => 'I.3.	The Bids and Awards Committee (BAC) perform its tasks and responsibilities in accordance with recent procurement policies and official issuances.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3284,
                  'parameter_item' => 'I.4.	The SMO prepares, evaluates, and submits the annual inventory of serviceable and non-serviceable facilities and equipment.',
                  'description' => 'I.4.	The SMO prepares, evaluates, and submits the annual inventory of serviceable and non-serviceable facilities and equipment.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3285,
                  'parameter_item' => 'I.5	All approved requests and procurement are published in Philippine Government Electronic Procurement System (PhilGEPS).',
                  'description' => 'I.5	All approved requests and procurement are published in Philippine Government Electronic Procurement System (PhilGEPS).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3286,
                  'parameter_item' => 'O.1.	The institution has an efficient and effective Supply Management System.',
                  'description' => 'O.1.	The institution has an efficient and effective Supply Management System.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3287,
                  'parameter_item' => 'O.2.	All procurement transactions are transparent.',
                  'description' => 'O.2.	All procurement transactions are transparent.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '53',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER F: RECORDS MANAGEMENT
              [
                  'id' => 3288,
                  'parameter_item' => 'S.1.	The institution has a system of records-keeping.',
                  'description' => 'S.1.	The institution has a system of records-keeping.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3289,
                  'parameter_item' => 'S.2.	The institution has a policies and procedures to ensure the security and confidentiality of records.',
                  'description' => 'S.2.	The institution has a policies and procedures to ensure the security and confidentiality of records.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3290,
                  'parameter_item' => 'S.3.	Policies and procedures on prompt release of records are in place.',
                  'description' => 'S.3.	Policies and procedures on prompt release of records are in place.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3291,
                  'parameter_item' => 'I.1.	The institution maintains a Records Management Office (RMO) managed by a qualified Records Officer.',
                  'description' => 'I.1.	The institution maintains a Records Management Office (RMO) managed by a qualified Records Officer.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3292,
                  'parameter_item' => 'I.2.	A records system is installed in offices where it allows easy access to information needed by concerned parties.',
                  'description' => 'I.2.	A records system is installed in offices where it allows easy access to information needed by concerned parties.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3293,
                  'parameter_item' => 'I.3.	The Human Resource Management Office (HRMO) maintains accurate, up-to-date and systematic records of faculty and staff.',
                  'description' => 'I.3.	The Human Resource Management Office (HRMO) maintains accurate, up-to-date and systematic records of faculty and staff.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3294,
                  'parameter_item' => 'I.4.	The following updated record compilations are made available to concerned parties:',
                  'description' => 'I.4.	The following updated record compilations are made available to concerned parties:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3295,
                  'parameter_item' => 'I.4.1.	minutes of the Board of Regents/Trustees meetings',
                  'description' => 'I.4.1.	minutes of the Board of Regents/Trustees meetings',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3294',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3296,
                  'parameter_item' => 'I.4.2.	minutes of the faculty meetings, e.g. minutes of the Academic Council meetings',
                  'description' => 'I.4.2.	minutes of the faculty meetings, e.g. minutes of the Academic Council meetings',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3294',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3297,
                  'parameter_item' => 'I.4.3.	faculty/non-teaching personnel individual files',
                  'description' => 'I.4.3.	faculty/non-teaching personnel individual files',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3294',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3298,
                  'parameter_item' => 'I.4.4.	faculty/non-teaching personnel performance evaluation and',
                  'description' => 'I.4.4.	faculty/non-teaching personnel performance evaluation and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3294',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3299,
                  'parameter_item' => 'I.4.5.	other records such as:',
                  'description' => 'I.4.5.	other records such as:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3294',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3300,
                  'parameter_item' => 'I.4.5.1. student directory',
                  'description' => 'I.4.5.1. student directory',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3301,
                  'parameter_item' => 'I.4.5.2. alumni directory',
                  'description' => 'I.4.5.2. alumni directory',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3302,
                  'parameter_item' => 'I.4.5.3. permanent records of students',
                  'description' => 'I.4.5.3. permanent records of students',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3303,
                  'parameter_item' => 'I.4.5.4. reports of Director/Dean',
                  'description' => 'I.4.5.4. reports of Director/Dean',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3304,
                  'parameter_item' => 'I.4.5.5. annual reports',
                  'description' => 'I.4.5.5. annual reports',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3305,
                  'parameter_item' => 'I.4.5.6. accomplishment/progress reports',
                  'description' => 'I.4.5.6. accomplishment/progress reports',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3306,
                  'parameter_item' => 'I.4.5.7. scholarship records',
                  'description' => 'I.4.5.7. scholarship records',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3307,
                  'parameter_item' => 'I.4.5.8. statistical data',
                  'description' => 'I.4.5.8. statistical data',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3308,
                  'parameter_item' => 'I.4.5.9. financial records of students',
                  'description' => 'I.4.5.9. financial records of students',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3309,
                  'parameter_item' => 'I.4.5.10. inventory of property',
                  'description' => 'I.4.5.10. inventory of property',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3310,
                  'parameter_item' => 'I.4.5.11. proceedings of administrative investigation (if any)		    and',
                  'description' => 'I.4.5.11. proceedings of administrative investigation (if any)		    and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3311,
                  'parameter_item' => 'I.4.5.12. others (please specify) ______.',
                  'description' => 'I.4.5.12. others (please specify) ______.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '3299',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3312,
                  'parameter_item' => 'O.1.	The institution has a commendable Records Management System.',
                  'description' => 'O.1.	The institution has a commendable Records Management System.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '54',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER G: INSTITUTIONAL PLANNING AND DEVELOPMENT
              [
                  'id' => 3313,
                  'parameter_item' => 'S.1.	The institution has an approved Strategic Development Plan (SDP)available in printed and/or electronic forms.',
                  'description' => 'S.1.	The institution has an approved Strategic Development Plan (SDP)available in printed and/or electronic forms.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '55',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3314,
                  'parameter_item' => 'S.2.	There is a system to monitor the implementation of the SDP.',
                  'description' => 'S.2.	There is a system to monitor the implementation of the SDP.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '55',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3315,
                  'parameter_item' => 'I.1.	The institution’s Planning and Development Unit plans, monitors and evaluates planned activities/targets.',
                  'description' => 'I.1.	The institution’s Planning and Development Unit plans, monitors and evaluates planned activities/targets.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '55',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3316,
                  'parameter_item' => 'I.2.	The planning process is a cooperative and participative endeavor of administration, the faculty, staff and the students.',
                  'description' => 'I.2.	The planning process is a cooperative and participative endeavor of administration, the faculty, staff and the students.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '55',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3317,
                  'parameter_item' => 'I.3.	The SDP is implemented, monitored, evaluated, reviewed, and updated regularly.',
                  'description' => 'I.3.	The SDP is implemented, monitored, evaluated, reviewed, and updated regularly.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '55',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3318,
                  'parameter_item' => 'O.1.	The SDP is congruent with the VMGO as well as with the local, regional and national development goals and agenda.',
                  'description' => 'O.1.	The SDP is congruent with the VMGO as well as with the local, regional and national development goals and agenda.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '55',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER H: PERFORMANCE OF ADMINISTRATIVE PERSONNEL
              [
                  'id' => 3319,
                  'parameter_item' => 'S.1.	The institution has an approved performance evaluation system for administrative personnel which includes the following items:',
                  'description' => 'S.1.	The institution has an approved performance evaluation system for administrative personnel which includes the following items:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3320,
                  'parameter_item' => 'S.1.1.	competence',
                  'description' => 'S.1.1.	competence',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3319',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3321,
                  'parameter_item' => 'S.1.2.	quality of work',
                  'description' => 'S.1.2.	quality of work',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3319',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3322,
                  'parameter_item' => 'S.1.3.	work ethic (punctuality, wise use of time, etc.)',
                  'description' => 'S.1.3.	work ethic (punctuality, wise use of time, etc.)',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3319',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3323,
                  'parameter_item' => 'S.1.4.	creative/innovative ability',
                  'description' => 'S.1.4.	creative/innovative ability',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3319',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3324,
                  'parameter_item' => 'S.1.5.	ability to handle internal and external pressures and',
                  'description' => 'S.1.5.	ability to handle internal and external pressures and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3319',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3325,
                  'parameter_item' => 'S.1.6.	interpersonal relations.',
                  'description' => 'S.1.6.	interpersonal relations.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3319',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3326,
                  'parameter_item' => 'I.1.	The institution regularly monitors and evaluates the performance of the administrative staff.',
                  'description' => 'I.1.	The institution regularly monitors and evaluates the performance of the administrative staff.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3327,
                  'parameter_item' => 'I.2.	The results of performance evaluation of administrative personnel are utilized:',
                  'description' => 'I.2.	The results of performance evaluation of administrative personnel are utilized:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3328,
                  'parameter_item' => 'I.2.1.	to improve performance and delivery of services and',
                  'description' => 'I.2.1.	to improve performance and delivery of services and',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3327',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3329,
                  'parameter_item' => 'I.2.2.	for promotion.',
                  'description' => 'I.2.2.	for promotion.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '3327',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 3330,
                  'parameter_item' => 'O.1.	The administrative personnel/staff have commendable performance.',
                  'description' => 'O.1.	The administrative personnel/staff have commendable performance.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                   'accreditation_template_id' => '20',
                  'template_parameter_id' => '56',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ]
          ];
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $builder->insertBatch($data);
        }

        public function down()
        {
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $db->simpleQuery('DELETE FROM '.$this->table.' WHERE id >= 3201 AND id <= 3330');
        }
}
