<?php namespace App\Database\Migrations;

class AddIndicatorsBseceav extends \CodeIgniter\Database\Migration {

        private $table = 'parameter_items';
        public function up()
        {
          $data = [
            //PARAMETER A: PRIORITIES AND RELEVANCE 2301
              [
                  'id' => 2301,
                  'parameter_item' => 'S.1. The institution’s research agenda is in consonance ¬¬¬with institutional, regional and national priorities concerned such as DOST, CHED-National Higher Education Research Agenda, NEDA, etc.',
                  'description' => 'S.1. The institution’s research agenda is in consonance ¬¬¬with institutional, regional and national priorities concerned such as DOST, CHED-National Higher Education Research Agenda, NEDA, etc.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2302,
                  'parameter_item' => 'S.2. The institution has an approved Research Manual',
                  'description' => 'S.2. The institution has an approved Research Manual',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2303,
                  'parameter_item' => 'I.1. The approved Research Agenda is implemented.',
                  'description' => 'I.1. The approved Research Agenda is implemented.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2304,
                  'parameter_item' => 'I.2. The following stakeholders participate in the formulation of research agenda as bases for identifying institutional thrusts and priorities:',
                  'description' => 'I.2. The following stakeholders participate in the formulation of research agenda as bases for identifying institutional thrusts and priorities:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2305,
                  'parameter_item' => 'I.2.1. administrators',
                  'description' => 'I.2.1. administrators',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '2304',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2306,
                  'parameter_item' => 'I.2.2. faculty',
                  'description' => 'I.2.2. faculty',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '2304',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2307,
                  'parameter_item' => 'I.2.3 students',
                  'description' => 'I.2.3 students',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '2304',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2308,
                  'parameter_item' => 'I.2.4. government agency representatives (DOST, CHED, NEDA, etc.)',
                  'description' => 'I.2.4. government agency representatives (DOST, CHED, NEDA, etc.)',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '2304',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2309,
                  'parameter_item' => 'I.2.5. other agencies (alumni, parents, etc.).',
                  'description' => 'I.2.5. other agencies (alumni, parents, etc.).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '2304',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2310,
                  'parameter_item' => 'I.3. Action researches to test theory in practice are conducted by faculty and students.',
                  'description' => 'I.3. Action researches to test theory in practice are conducted by faculty and students.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2311,
                  'parameter_item' => 'I.4. Team/ collaborative and interdisciplinary research is encouraged',
                  'description' => 'I.4. Team/ collaborative and interdisciplinary research is encouraged',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2312,
                  'parameter_item' => 'I.5. Research outputs are published in refereed national and/or international journals',
                  'description' => 'I.5. Research outputs are published in refereed national and/or international journals',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2313,
                  'parameter_item' => 'O.1. Priority researches are identified and conducted.',
                  'description' => 'O.1. Priority researches are identified and conducted.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2314,
                  'parameter_item' => 'O.2. Research results are published',
                  'description' => 'O.2. Research results are published',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER B: FUNDING AND OTHER RESOURCES
              [
                  'id' => 2315,
                  'parameter_item' => 'S.1. The institution has an approved and adequate budget for research',
                  'description' => 'S.1. The institution has an approved and adequate budget for research',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2316,
                  'parameter_item' => 'S.2. There are provisions for the following',
                  'description' => 'S.2. There are provisions for the following',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2317,
                  'parameter_item' => 'S.2.1. facilities and equipment such as Internet, statistical software, and other ICT resources',
                  'description' => 'S.2.1. facilities and equipment such as Internet, statistical software, and other ICT resources',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '2316',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2318,
                  'parameter_item' => 'S.2.2. research staff',
                  'description' => 'S.2.2. research staff',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '2316',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2319,
                  'parameter_item' => 'S.2.3. supplies and materials',
                  'description' => 'S.2.3. supplies and materials',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '2316',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2320,
                  'parameter_item' => 'S.2.4. workplace',
                  'description' => 'S.2.4. workplace',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '2316',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2321,
                  'parameter_item' => 'I.1. allocates adequate funds for the conduct of faculty and student research',
                  'description' => 'I.1. allocates adequate funds for the conduct of faculty and student research',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2322,
                  'parameter_item' => 'I.2. establishes linkages with the local/national/international/ agencies for funding support and assistance',
                  'description' => 'I.2. establishes linkages with the local/national/international/ agencies for funding support and assistance',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2323,
                  'parameter_item' => 'I.3. maintains a functional and long-range program of faculty/staff development to enhance research capability and competence.',
                  'description' => 'I.3. maintains a functional and long-range program of faculty/staff development to enhance research capability and competence.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2324,
                  'parameter_item' => 'I.4. encourages the conduct of externally funded researches',
                  'description' => 'I.4. encourages the conduct of externally funded researches',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2325,
                  'parameter_item' => 'O.1. The Research Program is adequately funded',
                  'description' => 'O.1. The Research Program is adequately funded',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '23',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER C: IMPLEMENTATION, MONITORING, EVALUATION AND UTILIZATION OF RESEARCH
              [
                  'id' => 2326,
                  'parameter_item' => 'S.1. There is a system of implementation, monitoring, evaluation and utilization of research outputs',
                  'description' => 'S.1. There is a system of implementation, monitoring, evaluation and utilization of research outputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2327,
                  'parameter_item' => 'S.2. The institution has a policy on Intellectual Property Rights (IPR).',
                  'description' => 'S.2. The institution has a policy on Intellectual Property Rights (IPR).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2328,
                  'parameter_item' => 'I.1. The institution/College/Academic Unit has a Research Unit managed by competent staff',
                  'description' => 'I.1. The institution/College/Academic Unit has a Research Unit managed by competent staff',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2329,
                  'parameter_item' => 'I.2. The Research Manual provides guidelines and procedures for the administration and conduct of research.',
                  'description' => 'I.2. The Research Manual provides guidelines and procedures for the administration and conduct of research.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2330,
                  'parameter_item' => 'I.3. The faculty conduct applied and operational researches in their fields of specialization in accordance with the thrusts and priorities of the program/institution',
                  'description' => 'I.3. The faculty conduct applied and operational researches in their fields of specialization in accordance with the thrusts and priorities of the program/institution',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2331,
                  'parameter_item' => 'I.4. The institution provides incentives to faculty researchers such as honoraria, service credits, deloading, etc',
                  'description' => 'I.4. The institution provides incentives to faculty researchers such as honoraria, service credits, deloading, etc',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2332,
                  'parameter_item' => 'I.5. The College/Academic Unit requires its students to conduct research, as a course requirement, (whenever applicable).',
                  'description' => 'I.5. The College/Academic Unit requires its students to conduct research, as a course requirement, (whenever applicable).',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2333,
                  'parameter_item' => 'I.6. The institution provides opportunities for advanced studies and/or training to enhance faculty/staff research competence',
                  'description' => 'I.6. The institution provides opportunities for advanced studies and/or training to enhance faculty/staff research competence',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2334,
                  'parameter_item' => 'I.7. Completed and on-going research studies are periodically monitored and evaluated in local and regional in-house reviews',
                  'description' => 'I.7. Completed and on-going research studies are periodically monitored and evaluated in local and regional in-house reviews',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2335,
                  'parameter_item' => 'I.8. Research outputs are utilized as inputs in',
                  'description' => 'I.8. Research outputs are utilized as inputs in',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2336,
                  'parameter_item' => 'I.8.1. institutional development',
                  'description' => 'I.8.1. institutional development',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '2335',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2337,
                  'parameter_item' => 'I.8.2. the improvement of instructional processes',
                  'description' => 'I.8.2. the improvement of instructional processes',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '2335',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2338,
                  'parameter_item' => 'I.8.3. the transfer of generated technology/knowledge to the community',
                  'description' => 'I.8.3. the transfer of generated technology/knowledge to the community',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '2335',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2339,
                  'parameter_item' => 'I.9. Packaged technologies and new information are disseminated to the target clientele through appropriate delivery systems',
                  'description' => 'I.9. Packaged technologies and new information are disseminated to the target clientele through appropriate delivery systems',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2340,
                  'parameter_item' => 'I.10. The institution ensures that',
                  'description' => 'I.10. The institution ensures that',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2341,
                  'parameter_item' => 'I.10.1. research outputs are protected by IPR laws',
                  'description' => 'I.10.1. research outputs are protected by IPR laws',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '2340',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2342,
                  'parameter_item' => 'I.10.2. faculty and students observe research ethics to avoid malpractices like plagiarism, fabrication of data, etc.',
                  'description' => 'I.10.2. faculty and students observe research ethics to avoid malpractices like plagiarism, fabrication of data, etc.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '2340',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2343,
                  'parameter_item' => 'O.1. Implementation, monitoring, evaluation and research utilization of outputs are effective',
                  'description' => 'O.1. Implementation, monitoring, evaluation and research utilization of outputs are effective',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '24',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER D: PUBLICATION AND DISSEMINATION
              [
                  'id' => 2344,
                  'parameter_item' => 'S.1 The institution has an approved and copyrighted Research Journal',
                  'description' => 'S.1 The institution has an approved and copyrighted Research Journal',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2345,
                  'parameter_item' => 'S.2. The institution has incentives for:',
                  'description' => 'S.2. The institution has incentives for:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2346,
                  'parameter_item' => 'S.2.1. paper presentations',
                  'description' => 'S.2.1. paper presentations',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2345',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2347,
                  'parameter_item' => 'S.2.2. journal publication',
                  'description' => 'S.2.2. journal publication',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2345',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2348,
                  'parameter_item' => 'S.2.3. outstanding research related performance',
                  'description' => 'S.2.3. outstanding research related performance',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2345',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2349,
                  'parameter_item' => 'S.2.4. patented outputs',
                  'description' => 'S.2.4. patented outputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2345',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2350,
                  'parameter_item' => 'I.1. The institution provides opportunities for the dissemination of research results in fora, conferences, seminars and other related means',
                  'description' => 'I.1. The institution provides opportunities for the dissemination of research results in fora, conferences, seminars and other related means',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2351,
                  'parameter_item' => 'I.2. The institution regularly publishes a research journal',
                  'description' => 'I.2. The institution regularly publishes a research journal',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2352,
                  'parameter_item' => 'I.3. Library exchange of research publications with other HEI’s and agencies is maintained.',
                  'description' => 'I.3. Library exchange of research publications with other HEI’s and agencies is maintained.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2353,
                  'parameter_item' => 'I.4. Research manuscript/technical reports are well-written, and edited following the institutional format.',
                  'description' => 'I.4. Research manuscript/technical reports are well-written, and edited following the institutional format.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2354,
                  'parameter_item' => 'I.5. The institution supports the researchers in all of the following activities:',
                  'description' => 'I.5. The institution supports the researchers in all of the following activities:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2355,
                  'parameter_item' => 'I.5.1. Instructional Materials Development',
                  'description' => 'I.5.1. Instructional Materials Development',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2354',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2356,
                  'parameter_item' => 'I.5.2. paper presentations, journal publication, classroom lectures and other similar activities',
                  'description' => 'I.5.2. paper presentations, journal publication, classroom lectures and other similar activities',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2354',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2357,
                  'parameter_item' => 'I.5.3. editorship/ writing in academic, scientific and professional journals',
                  'description' => 'I.5.3. editorship/ writing in academic, scientific and professional journals',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2354',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2358,
                  'parameter_item' => 'I.5.4. thesis/dissertation advising outputs',
                  'description' => 'I.5.4. thesis/dissertation advising outputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2354',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2359,
                  'parameter_item' => 'I.5.5. patenting of research outputs',
                  'description' => 'I.5.5. patenting of research outputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '2354',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2360,
                  'parameter_item' => 'I.6. Research results are published preferably in refereed journals',
                  'description' => 'I.6. Research results are published preferably in refereed journals',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2361,
                  'parameter_item' => 'I.7. Research results are disseminated to the target clientele',
                  'description' => 'I.7. Research results are disseminated to the target clientele',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2362,
                  'parameter_item' => 'I.8. The College/Academic Unit generates income from patents, licenses, copyrights, and other research outputs',
                  'description' => 'I.8. The College/Academic Unit generates income from patents, licenses, copyrights, and other research outputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2363,
                  'parameter_item' => 'O.1. Research outputs are published in refereed journals',
                  'description' => 'O.1. Research outputs are published in refereed journals',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2364,
                  'parameter_item' => 'O.2. Research outputs are utilized',
                  'description' => 'O.2. Research outputs are utilized',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2365,
                  'parameter_item' => 'O.3. Patented and copyrighted research outputs are commercialized',
                  'description' => 'O.3. Patented and copyrighted research outputs are commercialized',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '15',
                  'template_parameter_id' => '25',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ]
          ];
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $builder->insertBatch($data);
        }

        public function down()
        {
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $db->simpleQuery('DELETE FROM '.$this->table.' WHERE id >= 2301 AND id <= 2365');
        }
}
