<?php namespace App\Database\Migrations;

class AddIndicatorsBseceavi extends \CodeIgniter\Database\Migration {

        private $table = 'parameter_items';
        public function up()
        {
          //PARAMETER A: PRIORITIES AND RELEVANCE 2401
          $data = [
              [
                  'id' => 2401,
                  'parameter_item' => 'S.1 The extension agenda is in consonance of local, regional and national development thrusts and priorities.',
                  'description' => 'S.1 The extension agenda is in consonance of local, regional and national development thrusts and priorities.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2402,
                  'parameter_item' => 'S.2 The College/Academic Unit of Electronics Engineering has a benchmark survey of the problems, needs priorities and resources of the community.',
                  'description' => 'S.2 The College/Academic Unit of Electronics Engineering has a benchmark survey of the problems, needs priorities and resources of the community.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2403,
                  'parameter_item' => 'S.3 The extension program reflects the VMGO.',
                  'description' => 'S.3 The extension program reflects the VMGO.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2404,
                  'parameter_item' => 'S.4. There is a pool of consultants/experts from various disciplines to serve in extension projects and activities.',
                  'description' => 'S.4. There is a pool of consultants/experts from various disciplines to serve in extension projects and activities.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2405,
                  'parameter_item' => 'S.5. The institutions has an approved and copyrighted Extension Manual',
                  'description' => 'S.5. The institutions has an approved and copyrighted Extension Manual',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2406,
                  'parameter_item' => 'I.1 The extension projects and activities implemented are based on the results of the benchmark survey.',
                  'description' => 'I.1 The extension projects and activities implemented are based on the results of the benchmark survey.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2407,
                  'parameter_item' => 'I.2 The extension projects and activities complement the curriculum of the Electronics Engineering program under review.',
                  'description' => 'I.2 The extension projects and activities complement the curriculum of the Electronics Engineering program under review.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2408,
                  'parameter_item' => 'I.3 A mutual exchange of resources and services between the College/ Academic Unit and the community is evident',
                  'description' => 'I.3 A mutual exchange of resources and services between the College/ Academic Unit and the community is evident',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2409,
                  'parameter_item' => 'I.4 Linkages with local, national, foreign, and non-governmental agencies are institutionalized',
                  'description' => 'I.4 Linkages with local, national, foreign, and non-governmental agencies are institutionalized',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2410,
                  'parameter_item' => 'O.1 Priority and relevant extension projects and activities are conducted',
                  'description' => 'O.1 Priority and relevant extension projects and activities are conducted',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '22',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //Parameter B: PLANNING, IMPLEMENTATION, MONITORING AND EVALUATION
              [
                  'id' => 2411,
                  'parameter_item' => 'S.1 There is a distinct office that manages the Extension Program.',
                  'description' => 'S.1 There is a distinct office that manages the Extension Program.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2412,
                  'parameter_item' => 'S.2 Instruments for monitoring and evaluation are available',
                  'description' => 'S.2 Instruments for monitoring and evaluation are available',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2413,
                  'parameter_item' => 'I.1 The administration, faculty, students and other stakeholders of the College/Academic Unit of Electronics Engineering participate in the planning and organization of extension program',
                  'description' => 'I.1 The administration, faculty, students and other stakeholders of the College/Academic Unit of Electronics Engineering participate in the planning and organization of extension program',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2414,
                  'parameter_item' => 'I.2 The administration, faculty and students are involved in the implementation and dissemination of extension programs',
                  'description' => 'I.2 The administration, faculty and students are involved in the implementation and dissemination of extension programs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2415,
                  'parameter_item' => 'I.3 The extension projects and activities serve varied clientele',
                  'description' => 'I.3 The extension projects and activities serve varied clientele',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2416,
                  'parameter_item' => 'I.4 The conduct of extension projects and activities is sustainable',
                  'description' => 'I.4 The conduct of extension projects and activities is sustainable',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2417,
                  'parameter_item' => 'I.5 Technologies/new knowledge are disseminated to the target clientele through appropriate extension delivery systems',
                  'description' => 'I.5 Technologies/new knowledge are disseminated to the target clientele through appropriate extension delivery systems',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2418,
                  'parameter_item' => 'I.6 The extension activities are documented in the form of:',
                  'description' => 'I.6 The extension activities are documented in the form of:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2419,
                  'parameter_item' => 'I.6.1. pamphlets',
                  'description' => 'I.6.1. pamphlets',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2420,
                  'parameter_item' => 'I.6.2. flyers',
                  'description' => 'I.6.2. flyers',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2421,
                  'parameter_item' => 'I.6.3. bulletins',
                  'description' => 'I.6.3. bulletins',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2422,
                  'parameter_item' => 'I.6.4. newsletters',
                  'description' => 'I.6.4. newsletters',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2423,
                  'parameter_item' => 'I.6.5. electronic resources',
                  'description' => 'I.6.5. electronic resources',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2424,
                  'parameter_item' => 'I.7 Periodic monitoring and evaluation of extension projects and activities are conducted',
                  'description' => 'I.7 Periodic monitoring and evaluation of extension projects and activities are conducted',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2425,
                  'parameter_item' => 'I.8 Results of monitoring and evaluation are disseminated and discussed with concerned stakeholders',
                  'description' => 'I.8 Results of monitoring and evaluation are disseminated and discussed with concerned stakeholders',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2426,
                  'parameter_item' => 'I.9. Re-planning of activities based on feedback is conducted',
                  'description' => 'I.9. Re-planning of activities based on feedback is conducted',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2427,
                  'parameter_item' => 'I.10. Accomplishment and terminal reports are filed and submitted on time.',
                  'description' => 'I.10. Accomplishment and terminal reports are filed and submitted on time.',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2428,
                  'parameter_item' => 'O.1. The Extension Program is well-planned, implemented, monitored, evaluated and disseminated',
                  'description' => 'O.1. The Extension Program is well-planned, implemented, monitored, evaluated and disseminated',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2429,
                  'parameter_item' => 'O.2. The Extension Program has contributed to the improvement on the quality of life of the target clientele/ beneficiaries',
                  'description' => 'O.2. The Extension Program has contributed to the improvement on the quality of life of the target clientele/ beneficiaries',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '26',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER C: FUNDING AND OTHER RESOURCES
              [
                  'id' => 2430,
                  'parameter_item' => 'S.1 There is an approved and adequate budget for extension',
                  'description' => 'S.1 There is an approved and adequate budget for extension',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2431,
                  'parameter_item' => 'S.2 There is a provision of:',
                  'description' => 'S.2 There is a provision of:',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2432,
                  'parameter_item' => 'S.2.1 facilities and equipment such as internet and other ICT resources',
                  'description' => 'S.2.1 facilities and equipment such as internet and other ICT resources',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2433,
                  'parameter_item' => 'S.2.1 extension staff',
                  'description' => 'S.2.1 extension staff',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2434,
                  'parameter_item' => 'S.2.1 supplies and materials',
                  'description' => 'S.2.1 supplies and materials',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2435,
                  'parameter_item' => 'S.2.1 workplace',
                  'description' => 'S.2.1 workplace',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2436,
                  'parameter_item' => 'I.1 The budget for the extension program is utilized as planned',
                  'description' => 'I.1 The budget for the extension program is utilized as planned',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2437,
                  'parameter_item' => 'I.2. Honoraria and other incentives (deloading, credit unit equivalent, etc.) to faculty involved in extension work are granted',
                  'description' => 'I.2. Honoraria and other incentives (deloading, credit unit equivalent, etc.) to faculty involved in extension work are granted',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2438,
                  'parameter_item' => 'I.3 The College/Academic Unit of Electronics Engineering sources out the following from other agencies',
                  'description' => 'I.3 The College/Academic Unit of Electronics Engineering sources out the following from other agencies',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2439,
                  'parameter_item' => 'I.3.1 additional funding',
                  'description' => 'I.3.1 additional funding',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2440,
                  'parameter_item' => 'I.3.1 technical assistance and service inputs',
                  'description' => 'I.3.1 technical assistance and service inputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2441,
                  'parameter_item' => 'O.1 The Extension Program is adequately funded',
                  'description' => 'O.1 The Extension Program is adequately funded',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '57',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              //PARAMETER D: COMMUNITY INVOLVEMENT AND PARTICIPATION IN THE INSTITUTION’S ACTIVITIES
              [
                  'id' => 2442,
                  'parameter_item' => 'S.1 There is a strategy for involving the community, government and private agencies in the Extension Program',
                  'description' => 'S.1 There is a strategy for involving the community, government and private agencies in the Extension Program',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '1',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2443,
                  'parameter_item' => 'I.1 The College/Academic Unit is committed to the service and development of the community',
                  'description' => 'I.1 The College/Academic Unit is committed to the service and development of the community',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2444,
                  'parameter_item' => 'I.1.1. initiates and maintains community development projects',
                  'description' => 'I.1.1. initiates and maintains community development projects',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2445,
                  'parameter_item' => 'I.1.2. involves the students, faculty, staff administrators with the projects',
                  'description' => 'I.1.2. involves the students, faculty, staff administrators with the projects',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2446,
                  'parameter_item' => 'I.1.3. coordinates its community programs and services with the target clientele',
                  'description' => 'I.1.3. coordinates its community programs and services with the target clientele',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2447,
                  'parameter_item' => 'I.2. There is community participation and involvement in extension activities in the following',
                  'description' => 'I.2. There is community participation and involvement in extension activities in the following',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2448,
                  'parameter_item' => 'I.2.1 planning',
                  'description' => 'I.2.1 planning',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2449,
                  'parameter_item' => 'I.2.2 implementation and dissemination',
                  'description' => 'I.2.2 implementation and dissemination',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2450,
                  'parameter_item' => 'I.2.3 monitoring and dissemination',
                  'description' => 'I.2.3 monitoring and dissemination',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2451,
                  'parameter_item' => 'I.2.4 out-sourcing of funds, materials and other service inputs',
                  'description' => 'I.2.4 out-sourcing of funds, materials and other service inputs',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2452,
                  'parameter_item' => 'I.2.5 utilization of technology, knowledge learned, skills acquired from the extension projects and activities',
                  'description' => 'I.2.5 utilization of technology, knowledge learned, skills acquired from the extension projects and activities',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '2',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ],
              [
                  'id' => 2453,
                  'parameter_item' => 'O.1 There is wholesome coordination between the Extension Program implementers and the target clientele/ beneficiaries',
                  'description' => 'O.1 There is wholesome coordination between the Extension Program implementers and the target clientele/ beneficiaries',
                  'document_needed_list' => '',
                  'tagged_documents' => '[]',
                  'parameter_section_id' => '3',
                  'accreditation_template_id' => '16',
                  'template_parameter_id' => '27',
                  'parent_parameter_item_id' => '0',
                  'status' => 'a',
                  'created_at' => date('Y-m-d H:i:s')
              ]
          ];
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $builder->insertBatch($data);
        }

        public function down()
        {
          $db      = \Config\Database::connect();
          $builder = $db->table($this->table);
          $db->simpleQuery('DELETE FROM '.$this->table.' WHERE id >= 2401 AND id <= 2453');
        }
}
